server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: discovery-server

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
